[package]
name = "mbcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
chrono = "0.4.24"
config = { version = "0.13.3", default-features = false, features = ["json5"] }
html2text = "0.5.1"
itertools = "0.10.5"
megalodon = "0.7.0"
oauth1-request = "0.6.0"
regex = "1.7.3"
reqwest = { version = "0.11.16", features = ["json"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
time = { version = "0.3.20", features = ["formatting"] }
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = [
  "env-filter",
  "local-time"
] }
